#include "ir.h"

#include <stddef.h>
#include <stdint.h>

#include "vm.h"

int amivm_ir_decode_words_base(struct amivm_ir_block *block,
                               const uint16_t *words, size_t word_count);
int amivm_ir_execute_base(const struct amivm_ir_block *block,
                          struct amivm_cpu_state *cpu, struct amivm_vm *vm);

static int supervisor_mode(const struct amivm_cpu_state *cpu) { return (cpu->sr & 0x2000u) != 0u; }
static void sync_a7_bank(struct amivm_cpu_state *cpu) { if ((cpu->sr & 0x2000u) == 0u) cpu->usp=cpu->a[7]; else if ((cpu->sr & 0x1000u) != 0u) cpu->msp=cpu->a[7]; else cpu->isp=cpu->a[7]; }
static int translate_stack_long(struct amivm_cpu_state *cpu, struct amivm_vm *vm,uint32_t logical,int write,uint32_t physical[4]) { unsigned i; if (vm==NULL || (logical&1u)!=0u) return -1; for(i=0;i<4u;++i) if(amivm_mmu_translate(cpu,vm,logical+i,write!=0,supervisor_mode(cpu),&physical[i])!=AMIVM_MMU_OK) return -1; return 0; }
static int write_stack_long(struct amivm_cpu_state *cpu,struct amivm_vm *vm,uint32_t logical,uint32_t value) { uint32_t p[4]; unsigned i; if(translate_stack_long(cpu,vm,logical,1,p)!=0)return -1; for(i=0;i<4u;++i){unsigned s=(3u-i)*8u;if(!amivm_write8(vm,p[i],(uint8_t)(value>>s)))return -1;}return 0; }
static int read_stack_long(struct amivm_cpu_state *cpu,struct amivm_vm *vm,uint32_t logical,uint32_t *value) { uint32_t p[4];uint8_t b[4];unsigned i;if(value==NULL||translate_stack_long(cpu,vm,logical,0,p)!=0)return -1;for(i=0;i<4u;++i)if(!amivm_read8(vm,p[i],&b[i]))return -1;*value=((uint32_t)b[0]<<24u)|((uint32_t)b[1]<<16u)|((uint32_t)b[2]<<8u)|b[3];return 0; }
static uint32_t index_value(const struct amivm_ir_op *op,const struct amivm_cpu_state *cpu) { uint32_t v=op->index_is_addr?cpu->a[op->index_reg]:cpu->d[op->index_reg];if(!op->index_long)v=(uint32_t)(int32_t)(int16_t)(v&0xffffu);return v*(uint32_t)op->index_scale; }
static uint32_t control_target(const struct amivm_ir_op *op,const struct amivm_cpu_state *cpu) { uint32_t base,index;if(op->ea_mode==AMIVM_IR_EA_AN)return cpu->a[op->reg];if(op->ea_mode==AMIVM_IR_EA_D16_AN)return cpu->a[op->reg]+(uint32_t)op->imm;if(op->ea_mode==AMIVM_IR_EA_PC_D16)return op->guest_pc+2u+(uint32_t)op->imm;if(op->ea_mode==AMIVM_IR_EA_D8_AN_XN||op->ea_mode==AMIVM_IR_EA_PC_D8_XN){base=op->ea_mode==AMIVM_IR_EA_D8_AN_XN?cpu->a[op->reg]:op->guest_pc+2u;if(op->base_suppress)base=0u;index=op->index_suppress?0u:index_value(op,cpu);return base+(uint32_t)(op->full_format?op->base_displacement:op->imm)+index;}return (uint32_t)op->imm; }
static int decode_index(struct amivm_ir_op *op,const uint16_t *words,size_t count,size_t *used) { struct amivm_ea_index_extension e;int rc=amivm_ea_parse_index_extension(words,count,&e);if(rc!=AMIVM_EA_PARSE_OK)return 0;if(e.full_format&&e.indirect_mode!=AMIVM_EA_INDIRECT_NONE)return 0;op->index_is_addr=e.index_is_addr;op->index_reg=e.index_reg;op->index_long=e.index_long;op->index_scale=e.index_scale;op->full_format=e.full_format;op->base_suppress=e.base_suppress;op->index_suppress=e.index_suppress;op->imm=e.brief_displacement;op->base_displacement=e.base_displacement;op->outer_displacement=e.outer_displacement;op->indirect_mode=e.indirect_mode;*used=e.words_consumed;return 1; }

int amivm_ir_decode_words(struct amivm_ir_block *block,const uint16_t *words,size_t word_count) {
 struct amivm_ir_op *op;uint16_t w;uint8_t condition;size_t wi,used;int32_t displacement;int rc=amivm_ir_decode_words_base(block,words,word_count);
 if(rc!=1||block==NULL||words==NULL||block->op_count==0u)return rc;op=&block->ops[block->op_count-1u];if(op->opcode!=AMIVM_IR_EXIT||op->guest_pc<block->guest_start_pc)return rc;wi=(size_t)((op->guest_pc-block->guest_start_pc)/2u);if(wi>=word_count)return rc;w=words[wi];
 if(w==0x4e75u){op->opcode=AMIVM_IR_RTS;op->instruction_bytes=2u;block->terminates=1;return 0;}
 if((w&0xfff8u)==0x4e90u||(w&0xfff8u)==0x4ed0u){op->opcode=(w&0x40u)?AMIVM_IR_JMP:AMIVM_IR_JSR;op->reg=(uint8_t)(w&7u);op->ea_mode=AMIVM_IR_EA_AN;op->instruction_bytes=2u;block->terminates=1;return 0;}
 if((w&0xfff8u)==0x4ea8u||(w&0xfff8u)==0x4ee8u){if(wi+1u>=word_count)return rc;op->opcode=(w&0x40u)?AMIVM_IR_JMP:AMIVM_IR_JSR;op->reg=(uint8_t)(w&7u);op->ea_mode=AMIVM_IR_EA_D16_AN;op->imm=(int16_t)words[wi+1u];op->instruction_bytes=4u;block->guest_end_pc=op->guest_pc+4u;block->terminates=1;return 0;}
 if(w==0x4ebau||w==0x4efau){if(wi+1u>=word_count)return rc;op->opcode=w==0x4efau?AMIVM_IR_JMP:AMIVM_IR_JSR;op->ea_mode=AMIVM_IR_EA_PC_D16;op->imm=(int16_t)words[wi+1u];op->instruction_bytes=4u;block->guest_end_pc=op->guest_pc+4u;block->terminates=1;return 0;}
 if((w&0xfff8u)==0x4eb0u||(w&0xfff8u)==0x4ef0u||w==0x4ebbu||w==0x4efbu){if(wi+1u>=word_count)return rc;if(!decode_index(op,&words[wi+1u],word_count-(wi+1u),&used))return rc;op->opcode=(w&0x40u)?AMIVM_IR_JMP:AMIVM_IR_JSR;if(w==0x4ebbu||w==0x4efbu){op->ea_mode=AMIVM_IR_EA_PC_D8_XN;op->reg=0u;}else{op->ea_mode=AMIVM_IR_EA_D8_AN_XN;op->reg=(uint8_t)(w&7u);}op->instruction_bytes=(uint8_t)(2u+used*2u);block->guest_end_pc=op->guest_pc+op->instruction_bytes;block->terminates=1;return 0;}
 if(w==0x4eb8u||w==0x4ef8u){if(wi+1u>=word_count)return rc;op->opcode=w==0x4ef8u?AMIVM_IR_JMP:AMIVM_IR_JSR;op->ea_mode=AMIVM_IR_EA_ABS_W;op->imm=(int16_t)words[wi+1u];op->instruction_bytes=4u;block->guest_end_pc=op->guest_pc+4u;block->terminates=1;return 0;}
 if(w==0x4eb9u||w==0x4ef9u){if(wi+2u>=word_count)return rc;op->opcode=w==0x4ef9u?AMIVM_IR_JMP:AMIVM_IR_JSR;op->ea_mode=AMIVM_IR_EA_ABS_L;op->imm=(int32_t)(((uint32_t)words[wi+1u]<<16u)|words[wi+2u]);op->instruction_bytes=6u;block->guest_end_pc=op->guest_pc+6u;block->terminates=1;return 0;}
 if((w&0xf000u)!=0x6000u)return rc;condition=(uint8_t)((w>>8u)&0xfu);if((w&0xffu)!=0u){if(condition!=1u)return rc;op->opcode=AMIVM_IR_BSR;op->imm=(int8_t)(w&0xffu);op->instruction_bytes=2u;block->terminates=1;return 0;}if(wi+1u>=word_count)return rc;displacement=(int16_t)words[wi+1u];if(condition==1u){op->opcode=AMIVM_IR_BSR;op->imm=displacement;op->instruction_bytes=4u;block->terminates=1;block->guest_end_pc=op->guest_pc+4u;return 0;}op->opcode=condition==0u?AMIVM_IR_BRANCH:AMIVM_IR_BRANCH_CC;op->condition=condition==0u?AMIVM_IR_CC_T:condition;op->guest_pc+=2u;op->imm=displacement-2;op->instruction_bytes=4u;block->terminates=1;block->guest_end_pc=op->guest_pc+2u;return 0;
}
int amivm_ir_execute(const struct amivm_ir_block *block,struct amivm_cpu_state *cpu,struct amivm_vm *vm){struct amivm_ir_block prefix;const struct amivm_ir_op *t;uint32_t ret,sp,target;int rc;if(block==NULL||cpu==NULL||block->op_count==0u)return amivm_ir_execute_base(block,cpu,vm);t=&block->ops[block->op_count-1u];if(t->opcode!=AMIVM_IR_BSR&&t->opcode!=AMIVM_IR_RTS&&t->opcode!=AMIVM_IR_JSR&&t->opcode!=AMIVM_IR_JMP)return amivm_ir_execute_base(block,cpu,vm);prefix=*block;prefix.ops[prefix.op_count-1u].opcode=AMIVM_IR_EXIT;prefix.ops[prefix.op_count-1u].instruction_bytes=2u;rc=amivm_ir_execute_base(&prefix,cpu,vm);if(rc<0)return rc;if(t->opcode==AMIVM_IR_JMP){cpu->pc=control_target(t,cpu);return 1;}if(t->opcode==AMIVM_IR_JSR){target=control_target(t,cpu);ret=t->guest_pc+t->instruction_bytes;sp=cpu->a[7]-4u;if(write_stack_long(cpu,vm,sp,ret)!=0)return -4;cpu->a[7]=sp;sync_a7_bank(cpu);cpu->pc=target;return 1;}if(t->opcode==AMIVM_IR_BSR){ret=t->guest_pc+t->instruction_bytes;sp=cpu->a[7]-4u;if(write_stack_long(cpu,vm,sp,ret)!=0)return -4;cpu->a[7]=sp;sync_a7_bank(cpu);cpu->pc=t->guest_pc+2u+(uint32_t)t->imm;return 1;}if(read_stack_long(cpu,vm,cpu->a[7],&ret)!=0)return -4;cpu->a[7]+=4u;sync_a7_bank(cpu);cpu->pc=ret;return 1;}
